### ISSUE TITLE
启动runIPWarden.py后就报错停止了

### ISSUE THREAD

**Issue by ciscochao** [EnnioX/IPWarden#3]
root@172.2.2.2~/data/IPWarden#python3 runIPWarden.py

Starting masscan 1.0.3 (http://bit.ly/14GZzcT) at 2023-07-18 09:10:32 GMT
 -- forced options: -sS -Pn -n --randomize-hosts -v --send-eth
Initiating SYN Stealth Scan
Scanning 1 hosts [65535 ports/host]
Traceback (most recent call last):
  File "runIPWarden.py", line 29, in <module>
    port_scan.main()  # IP、端口、协议扫描
  File "/root/data/IPWarden/scan/port_scan.py", line 95, in main
    common.result_to_mysql(read_masscan_result(), 'iplist')
  File "/root/data/IPWarden/scan/port_scan.py", line 28, in read_masscan_result
    xml_obj = xmltodict.parse(f.read())
  File "/usr/local/lib/python3.6/site-packages/xmltodict.py", line 378, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0

**Comment by ciscochao** [comment]
root@172.2.2.2~/data/IPWarden#python3 runIPWarden.py

Starting masscan 1.0.3 (http://bit.ly/14GZzcT) at 2023-07-18 09:34:28 GMT
 -- forced options: -sS -Pn -n --randomize-hosts -v --send-eth
Initiating SYN Stealth Scan
Scanning 1 hosts [65535 ports/host]
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/pandas/core/indexes/base.py", line 2898, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'url'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "runIPWarden.py", line 40, in <module>
    nuclei.main()  # nuclei漏洞扫描，基于web_scan
  File "/root/data/IPWarden/nuclei.py", line 56, in main
    make_urltxt()
  File "/root/data/IPWarden/nuclei.py", line 29, in make_urltxt
    ip_list = portsdata['url'].unique()
  File "/usr/local/lib64/python3.6/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib64/python3.6/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'url'

**Comment by luyii-code-1** [comment]
pip拉库先

**Comment by luyii-code-1** [comment]
pip install -r IPWarden\requirements.txt
